apiVersion: v1alpha
kind: testcafe

# Sauce Labs specific information
sauce:
  region: eu-central-1 # or us-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    name: TestCafe Cross Browser tests with SauceCTL
    tags:
      - testcafe
      - cross browser
    build: "TestCafe: Cross Browser test set - $DATE"

# Testcafe specific info
testcafe:
  version: 1.18.3
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./

# Tests
suites:
  - name: "Testcafe - Cross Browser - Swag Labs Login - Windows-Chrome"
    browserName: chrome
    platformName: "Windows 10"
    # Available resolutions on Windows:
    # - '800x600'
    # - '1024x768'
    # - '1152x864'
    # - '1280x768'
    # - '1280x800'
    # - '1280x960'
    # - '1280x1024'
    # - '1400x1050'
    # - '1440x900'
    # - '1600x1200'
    # - '1680x1050'
    # - '1920x1080'
    # - '1920x1200'
    # - '2560x1600'
    screenResolution: "1600x1200"
    src:
      # test files glob
      - "**/login.*"
  - name: "Testcafe - Cross Browser - Swag Labs Login - Windows-Microsoft Edge"
    browserName: microsoftedge
    platformName: "Windows 10"
    screenResolution: "1600x1200"
    src:
      # test files glob
      - "**/login.*"
  - name: "Testcafe - Cross Browser - Swag Labs Login - Windows-Firefox"
    browserName: firefox
    platformName: "Windows 10"
    screenResolution: "1600x1200"
    src:
      # test files glob
      - "**/login.*"
  - name: "Testcafe - Cross Browser - Swag Labs Login - Mac 11-Chrome"
    browserName: chrome
    platformName: "macOS 11.00"
    # Available resolutions on Mac 11:
    # - '1024x768'
    # - '1152x864'
    # - '1280x960'
    # - '1376x1032'
    # - '1440x900'
    # - '1600x1200'
    # - '1920x1440'
    # - '2048x1536'
    screenResolution: "1600x1200"
    src:
      # test files glob
      - "**/login.*"
  - name: "Testcafe - Cross Browser - Swag Labs Login - Mac 11-Firefox"
    browserName: firefox
    platformName: "macOS 11.00"
    screenResolution: "1600x1200"
    src:
      # test files glob
      - "**/login.*"
  - name: "Testcafe - Cross Browser - Swag Labs Login - Mac 11-MicrosoftEdge"
    browserName: microsoftedge
    platformName: "macOS 11.00"
    screenResolution: "1600x1200"
    src:
      # test files glob
      - "**/login.*"
  - name: "Testcafe - Cross Browser - Swag Labs Login - Mac 11-Safari"
    browserName: safari
    platformName: "macOS 11.00"
    screenResolution: "1600x1200"
    src:
      # test files glob
      - "**/login.*"
# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
# artifacts:
#   download:
#     directory: ./artifacts
#     match:
#       - "*"
#     when: always
