name: TestCafe Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: testcafe/tests/specs
      - name: Run TestCafe tests
        run: npm test
        working-directory: testcafe/tests/specs
