name: Gitpod Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: gitpod/test/specs/selenium
      - name: Run Selenium tests
        run: npm test
        working-directory: gitpod/test/specs/selenium

  appium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: gitpod/test/specs/appium
      - name: Run Appium tests
        run: npm test
        working-directory: gitpod/test/specs/appium
