apiVersion: v1alpha
kind: cypress
sauce:
  region: eu-central-1 # or us-west-1
  concurrency: 2
  metadata:
    name: Cypress Dependency Test
    tags:
      - cypress
      - dependencies
    build: "Cypress: Axe dependency test - $DATE"
npm:
  packages:
    "axe-core": "^4.3.3"
    "cypress-axe": "^0.13.0"
docker:
  fileTransfer: mount
cypress:
  version: 8.3.0
  configFile: "cypress.json"  # We determine related files based on the location of the config file.
suites:
  # Chrome
  - name: "Swag Labs Login Axe Test"
    browser: "chrome"
    platformName: "Windows 10"
    screenResolution: "1400x1050"
    config:
      testFiles: [ "**/axe.*" ]
