name: WebdriverIO Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  webdriver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: webdriverio/webdriver/examples
      - name: Run WebDriver tests
        run: npm test
        working-directory: webdriverio/webdriver/examples

  appium-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: webdriverio/appium-web/examples
      - name: Run Appium Web tests
        run: npm test
        working-directory: webdriverio/appium-web/examples

  appium-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: webdriverio/appium-app/examples
      - name: Run Appium App tests
        run: npm test
        working-directory: webdriverio/appium-app/examples
