name: Playwright

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  saucectl:
    name: Saucectl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run saucectl
        uses: saucelabs/saucectl-run-action@v4
        with:
          concurrency: 10
          working-directory: "playwright"
  reporter:
    name: Reporter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: playwright
        run: npm install
      - name: Install Playwright browsers
        working-directory: playwright
        run: npx playwright install
      - name: Run local tests
        working-directory: playwright
        run: npm run test.local
  remote:
    name: Remote Grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: playwright
        run: npm install
      - name: Install Playwright browsers
        working-directory: playwright
        run: npx playwright install
      - name: Run remote tests
        working-directory: playwright
        run: npm run test.remote
