name: Puppeteer Tests

on:
  push:
    branches:
      - main
    paths:
      - '**/puppeteer/**'
  pull_request:
    paths:
      - '**/puppeteer/**'
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
        working-directory: puppeteer
      - name: Run Puppeteer tests
        run: npm test
        working-directory: puppeteer/test/specs
