name: Selenium-webdriver JS

on:
  push:
    # Only trigger if files in this path changed
    paths:
      - 'selenium/**'
      - '.github/workflows/selenium.js.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  pull_request:
    # Only trigger if files in this path changed
    paths:
      - 'selenium/**'
      - '.github/workflows/selenium.js.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    name: test-${{matrix.os}}-${{matrix.node-version}}
    defaults:
      run:
        working-directory: ./selenium/
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [windows-latest, macOS-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests in US
        run: npm run test.safari.us
