name: TestCafe Tests

on:
  push:
    branches:
      - main
    paths:
      - '**/testcafe/**'
  pull_request:
    paths:
      - '**/testcafe/**'
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
        working-directory: testcafe/tests/specs
      - name: Run TestCafe tests
        run: npm test
        working-directory: testcafe/tests/specs
