name: WebdriverIO - Appium Web - Best Practices

on:
  push:
    # Only trigger if files in this path changed
    paths:
      - 'webdriverio/appium-web/best-practices/**'
      - '.github/workflows/wdio.appium.web.bp.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  pull_request:
    # Only trigger if files in this path changed
    paths:
      - 'webdriverio/appium-web/best-practices/**'
      - '.github/workflows/wdio.appium.web.bp.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./webdriverio/appium-web/best-practices/
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests Android
        run: npm run test.saucelabs.android.us -- --maxInstances=10

      - name: Run tests iOS
        run: npm run test.saucelabs.ios.us -- --maxInstances=10
