name: WebdriverIO - Appium App - UpDownload files

on:
  push:
    # Only trigger if files in this path changed
    paths:
      - 'webdriverio/appium-app/examples/up-download-file/**'
      - '.github/workflows/wdio.appium.app.up.download.files.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  pull_request:
    # Only trigger if files in this path changed
    paths:
      - 'webdriverio/appium-app/examples/up-download-file/**'
      - '.github/workflows/wdio.appium.app.up.download.files.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./webdriverio/appium-app/examples/up-download-file/
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run upload/download tests Android Emulators
        run: npm run test.sauce.android.emulator.us

      - name: Run tests upload tests iOS Simulators
        run: npm run test.sauce.ios.simulator.us
