name: WebdriverIO - Webdriver - Examples - TS
env:
  PWD: ./webdriverio/webdriver/examples/typescript/

on:
  push:
    # Only trigger if files in this path changed
    paths:
      - ${{ PWD }}
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ master ]
  pull_request:
    # Only trigger if files in this path changed
    paths:
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ${{ PWD }}
        run: npm install

      - name: Run tests
        working-directory: ${{ PWD }}
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run test
